spring:
  application:
    name: 'Mybatis-Auditing-Sample'
  datasource:
    url: 'jdbc:postgresql://10.9.108.139:5432/sample_db'
    username: maxtropy
    password: maxtropy
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    auto-mapping-unknown-column-behavior: warning
    map-underscore-to-camel-case: true
  mapper-locations: "classpath:mappers/*.xml"
  plugin:
    auditing:
      enabled: true